### PR TITLE
added customised help functionality

### PR DESCRIPTION
**Pull request by Deb2001**
New customised help commands for all functionalities 
<details>
<summary>
Here are some examples:
</summary>

</details>

### CODE REVIEW

**Review by sdk2k01 — CHANGES_REQUESTED** [review]
cool, but we can make it cooler, and that is exactly what need to be done ;)

**Review by sdk2k01 — COMMENTED** [review]
lgtm....now requesting @Dsantra92 for final review

**Review by sdk2k01 — APPROVED** [review]
LGTM....ready to merge after final review

**Comment by Dsantra92** [comment]
LessGOooo. 🚀

**Pull request merged**
