### PR TITLE
added educational meme functionality (redditAPI)

### PR DESCRIPTION
**Pull request by sdk2k01**
@Dsantra92 
The functionality for educational memes based on redditAPI co-authored by @Rajrup911 & @SHREEOM0611 has been added, with proper handing for errors.
Some examples are : 
<details>
<summary>Basic memes functionalities</summary>
Screenshot 2021-08-19 at 10 36 15 PM
</details>
<details>
<summary>Handling for basic errors</summary>
Screenshot 2021-08-19 at 10 36 29 PM
</details>
<details>
<summary>Turning the magical wand of autoposting on</summary>
Screenshot 2021-08-19 at 10 37 06 PM
</details>
<details>
<summary>Autoposting in action</summary>
Screenshot 2021-08-19 at 10 36 43 PM
</details>

Hope you like it UwU

### CODE REVIEW

**Comment by Dsantra92** [comment]
Just one thing, weren't they supposed to make the pull request? These commits are authored by you.

**Comment by sdk2k01** [comment]
> Just one thing, weren't they supposed to make the pull request? These commits are authored by you.

Yeah, Rajrup was supposed to make the pull request but his code ran a few problems (related to opening files) so i made some minor changes.

**Comment by Dsantra92** [comment]
Ah!! But that is not how things are meant to be!! :smile_in_pain:
Let's just discuss this in the next meeting.

**Comment by sdk2k01** [comment]
> Ah!! But that is not how things are meant to be!! :smile_in_pain:
> Let's just discuss this in the next meeting.

okay

**Comment by sdk2k01** [comment]
> Ah!! But that is not how things are meant to be!! :smile_in_pain:
> Let's just discuss this in the next meeting.

**Pull request closed without merging**
